apiVersion: apps/v1
kind: Deployment
metadata:
  name: streampod-engine
spec:
  selector:
    matchLabels:
      run: streampod-engine
  replicas: 2
  template:
    metadata:
      labels:
        run: streampod-engine
    spec:
      containers:
      - name: streampod-engine-pod
        image: ocano/streampod_engine
        ports:
        - containerPort: 8080

## Simple Prototype Deployment - ocano 6/16/21
## Supports ECR images.